
dataset:
  name: wotr
  classes:
    - fire_hydrant
    - blind_road
    - car
    - sign
    - pole
    - green_light
    - reflective_cone
    - ashcan
    - tree
    - bus
    - red_light
    - warning_column
    - motorcycle
    - crosswalk
    - dog
    - tricycle
    - person
    - bicycle
    - roadblock
    - truck
  file_id: 11Idy50HhzedOXxpxYuoecfqMNHGcxVfj
  output_file: wotr_dataset.zip
  extract_dir: data/raw
  extract_folder: WOTR
  raw_data_path: data/raw/WOTR
  processed_data_path: data/processed/wotr_yolo_format
  wotr_config_path : config/wotr_config.yaml

output_dir_path : outputs

training:
  epochs: 1
  imgsz: 640
  batch_size: -1
  device: mps
  training_output_dir: outputs
  model_name: yolov11-wotr
  weights_path: models/yolov11/yolo11n.pt

deployment:
  models_dir: models/
  tflite_output_dir: models/tflite
  onnx_output_dir: models/onnx

mlflow:
  tracking_uri: file:///Users/macbook/PycharmProjects/object_detection_pfe/mlruns
  experiment_name: YOLOv11_Object_Detection


