path: /Users/macbook/PycharmProjects/object_detection_pfe/data/processed/wotr_yolo_format

train: images/train
val: images/val
test: images/test

nc: 20  # number of classes

names:
  - fire_hydrant
  - blind_road
  - car
  - sign
  - pole
  - green_light
  - reflective_cone
  - ashcan
  - tree
  - bus
  - red_light
  - warning_column
  - motorcycle
  - crosswalk
  - dog
  - tricycle
  - person
  - bicycle
  - roadblock
  - truck
